//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Catalog.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modules.Catalog.Application.CatalogResources", typeof(CatalogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand deleted.
        /// </summary>
        public static string Brand_Deleted {
            get {
                return ResourceManager.GetString("Brand Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand saved.
        /// </summary>
        public static string Brand_Saved {
            get {
                return ResourceManager.GetString("Brand Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands exported.
        /// </summary>
        public static string Brands_Exported {
            get {
                return ResourceManager.GetString("Brands Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands imported.
        /// </summary>
        public static string Brands_Imported {
            get {
                return ResourceManager.GetString("Brands Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted.
        /// </summary>
        public static string Product_Deleted {
            get {
                return ResourceManager.GetString("Product Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product saved.
        /// </summary>
        public static string Product_Saved {
            get {
                return ResourceManager.GetString("Product Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products exported (#{0}).
        /// </summary>
        public static string Products_Exported {
            get {
                return ResourceManager.GetString("Products Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products imported (#{0}).
        /// </summary>
        public static string Products_Imported {
            get {
                return ResourceManager.GetString("Products Imported", resourceCulture);
            }
        }
    }
}
