variables:
- group: global
- name: buildEnabled
  value: 'true'
- name: testEnabled
  value: 'true'
- name: deployEnabled
  value: 'true'

trigger:
  tags:
    include:
    - '*'
  batch: 'true'
  branches:
    include:
      - master
      - develop
      - releases/*
      - features/*
      - hotfixes/*
      - bugfixes/*
  paths:
    exclude:
      - README.md

pr:
  autoCancel: 'true'
  branches:
    include:
      - master
      - releases/*

resources:
- repo: self
  fetchDepth: '0'

#######################################################################################################
# VERSION
#
stages:
- stage: version
  displayName: Version stage
  jobs:
  - template: ./templates/version.yml

#######################################################################################################
# BUILD
#
- stage: build
  displayName: Build stage
  condition: and(succeeded(), eq(variables['buildEnabled'], 'true'))
  jobs:
  - template: ./templates/build.yml
    parameters:
      buildConfiguration: 'Release'
      buildSolution: '$(Build.SourcesDirectory)/*.sln'

#######################################################################################################
# TEST
#
- stage: test
  displayName: Test stage
  condition: and(succeeded(), eq(variables['testEnabled'], 'true'))
  jobs:
  - template: ./templates/test.yml
    parameters:
      buildConfiguration: 'Release'
      testProjects: '$(Build.SourcesDirectory)/tests/*Tests/*.csproj'

#######################################################################################################
# DEPLOY
#
- stage: deploy_dev
  displayName: Deploy stage (dev)
  condition: and(succeeded(), eq(variables['deployEnabled'], 'true'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: ./templates/deploy.yml
    parameters:
      azureSubscription: dev-bitbaukasten-shop # =service connection name
      environment: 'dev'

- stage: deploy_tst
  displayName: Deploy stage (tst)
  condition: and(succeeded(), eq(variables['deployEnabled'], 'true'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases'))
  jobs:
  - template: ./templates/deploy.yml
    parameters:
      azureSubscription: dev-bitbaukasten-shop # =service connection name
      environment: 'tst'

- stage: deploy_prd
  displayName: Deploy stage (prd)
  condition: and(succeeded(), eq(variables['deployEnabled'], 'true'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases'))
  jobs:
  - template: ./templates/deploy.yml
    parameters:
      azureSubscription: dev-bitbaukasten-shop # =service connection name
      environment: 'prd'