#######################################################################################################
# VERSION
#
jobs:
  - job: version
    displayName: Version job
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      # system.debug: true
      MinVerDefaultPreReleaseIdentifiers: preview.0
      # MinVerBuildMetadata: $(Build.SourceVersion) # use git commit hash in version
    steps:
      - checkout: self
        fetchDepth: '0'

      - task: DotNetCoreCLI@2
        displayName: 'Install version tool'
        inputs:
          command: 'custom'
          custom: 'tool'
          arguments: 'install --global minver-cli --version 4.3.0'

      - powershell: |
          $version = $(minver -v d) # https://github.com/adamralph/minver#options
          $buildName = "$version" # + "_" + $env:BUILD_SOURCEBRANCHNAME
          Write-Host "##vso[build.updatebuildnumber]$buildName"
          Write-Host "##vso[task.setvariable variable=BUILD_VERSION;isOutput=true]$buildName"
        displayName: Calculate version
        name: CalculateVersion

      - powershell: |
          Get-ChildItem Env:
        displayName: Show environment variables